image: publysher/hugo

before_script:
  - hugo version

pages:
  stage: deploy
  environment: Production
  script:
    - hugo -d ./builds
    - cp -R ./builds/* /var/www/website
  artifacts:
    paths:
    - public
  only:
  - master
