image: jojomi/hugo:0.17

before_script:
  - hugo version
  - apk add --update -y git
  - git submodule update --init --recursive

pages:
  stage: deploy
  environment: Production
  script:
    - hugo -v
  artifacts:
    paths:
    - public
  only:
  - master
