image: publysher/hugo

before_script:
  - hugo version
  - ls
  - pwd
  - tree ./build

pages:
  stage: deploy
  environment: Production
  script:
    - hugo -d ./builds
    - cp -R ./build/* /var/www/website
  artifacts:
    paths:
    - public
  only:
  - master
