## Basic Configuration

baseurl = "https://sadmansk.com"
builddrafts = false
canonifyurls = false
languagecode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Sadman Kazi"
title = "Sadman Kazi"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Sadman Kazi"
intro = "Software Engineering student @ UWaterloo"
description = "Open source enthusiast, software architecture and cyber security nerd. <br/> I have experience in building embedded systems, network programming, and game engine development."
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Sadman Kazi personal website"
keywords = "software,engineer,developer,programmer"

## Social Accounts
[params.social]
github = "sadmansk"
linkedin = "sadmansk"
twitter = "sadman_k"
stackoverflow = "sadmansk"
gitlab = "sadmansk"
email = "sadmansk@protonmail.com"

## Extras
[params.extra]
copyright = "© 2017. Sadman Kazi. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = true
hightlightjs = true

## Main Menu
#[[menu.main]]
#    name = "blog"
#    weight = 100
#    identifier = "blog"
#    url = "/blog/"
[[menu.main]]
    name = "resume"
    identifier = "resume"
    weight = 100
    url = "/resume.pdf"
[[menu.main]]
    name = "projects"
    identifier = "projects"
    weight = 200
    url = "/projects/"
[[menu.main]]
    name = "blog"
    identifier = "blog"
    weight = 300
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 400
    url = "/about/"
