## Basic Configuration

baseurl = "https://sadmansk.com"
builddrafts = false
canonifyurls = false
languagecode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Sadman Kazi"
title = "Sadman Kazi"

theme = "manis"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
#googleAnalytics = "XYZ"
enableRobotsTXT = true

# Copyright notice. Note: You can use HTML tag here
copyright = "© 2019 Sadman Kazi. <a href=\"http://creativecommons.org/licenses/by/3.0/\">Some Rights Reserved</a>."
pluralizeListTitles = false

# Minimum number of posts before paginate navigation show up
paginate = 10

# Code Highlighting (Chroma)
pygmentsCodeFences = true
pygmentsUseClasses = true

## Site Settings
[params]
    author = "Sadman Kazi"
    intro = "Software Engineering student @ UWaterloo"
    description = "Open source enthusiast, software architecture and cyber security nerd."
    authorimage = "headshot.jpg"
    dateformat = "Jan 2, 2006"

    tagline = "random tidbits"
    keywords = "software,engineer,developer,programmer,security,open source,game engine"

    # If true give attribution to this theme
	themeAttrib = true

	# URL to license file, can be outside of your domain
	#licenseURL = "/about/license"

	# Configure which sections for Latest Posts
	mainSections = ["blog"]

	# Configure which sections for Latest Works
	workSections = ["projects"]

	# List of sections that support disqus comments
	disqusSections = [ "blog" ]

	# List of sections that support utterances comments
	utterancesSections = [ "blog" ]

	# Utterances Configuration
	utterancesRepo = ""
	utterancesTheme = "github-light"
	utterancesLabel = ""

	# 404 Configuration
	head404 = "Sorry, I can't find what you want."
	sub404 = "Back to <a href='/'>Home</a>."

	# Color of your website's accent
	#colorTheme = "#ff6565"

	# Maximum number of item in Latest Posts or Works
	latestCount = 5

	# Path to site's favicon image
	#faviconImg = ""

	# Code Highlighting (HighlightJS)
	highlightJs = false
	highlightJsLanguages = [ "go" ]
	highlightJsStyle = "ocean"

    github = "sadmansk"
    linkedin = "sadmansk"
    twitter = "sadman_k"
    #stackoverflow = "sadmansk"
    gitlab = "sadmansk"
    keybase = "sadmansk"
    email = "me@sadmansk.com"

## Main Menu
[[menu.main]]
    name = "resume"
    identifier = "resume"
    weight = 100
    url = "/resume.pdf"
[[menu.main]]
    name = "projects"
    identifier = "projects"
    weight = 200
    url = "/projects/"
[[menu.main]]
    name = "blog"
    identifier = "blog"
    weight = 300
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 400
    url = "/about"
